name: Deploy to Lower environments (manual)  
run-name: 'Deploy to Lower environments (manual) - ${{ format(' {0} | {1} ', inputs.environment, inputs.git_tag ) }}'

on: 
  workflow_dispatch:
    inputs:
      git_tag: 
        description: 'Git tag for the Docker image' 
        required: true 
        default: '' 
      environment: 
        description: 'The name of the environment to be deployed'     
        required: true 
        default: 'develop' 
        type: choice 
        options: 
        - develop 
        - cloudqa


jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - run : echo "Hello World"

    

